name: perform check and convert code to zip

on:
  push:
    branches:
      - master
jobs:
  zip_files:
    image: alpine
    before_script:
      - apk add --update zip
    script:
      - |
      for d in */ ; do
         cd $d; zip -r ../${d%/}.zip *; cd ..
      done
    artifacts:
      paths:
        - '*.zip'