# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push: #action (pull, push)
    branches: [ "main" ]
    
env:
  MONGO_URI: Monday
  NODE_ENV: development
  USER_KEY: nouserkey
  
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: manifest.json
          dest: ziped/result.zip
      - run: npm ci
      - run: npm run start
